### ISSUE TITLE
Common use reaches API rate limit

### ISSUE THREAD

**Issue by lightsing** [penguin-statistics/backend#19]
![Snipaste_2020-01-26_20-16-03](https://user-images.githubusercontent.com/15951701/73135052-e1fe1600-4078-11ea-86de-8a2f1ca785c7.png)

**Comment by GalvinGao** [comment]
At that time our Sentry plan was limited to a small number of issues that we are able to report to Sentry per month, and it was exceeding the limit so Sentry has blocked the request. (btw this has fixed because Sentry has given us free Open Source plan that allow us to report much more issues per month now)

It's not our service that rate limits the request, so this is not a legit issue ;)

Closing.
